### ISSUE TITLE
weexpack plugin add weex-chart 报错，怎么处理？？？

### ISSUE THREAD

**Issue by shangwfa** [weexteam/weex-pack#103]
weexpack plugin add weex-chart
Fetching plugin "weex-chart" via npm
Installing "weex-chart" for android
Fetching plugin "weex-gcanvas" via npm
Installing "weex-gcanvas" for android
Android Studio project detected
ANDROID_HOME=/Users/menmen/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
Unzipping /Users/menmen/.gradle/wrapper/dists/gradle-2.14.1-all/53l0mv9mggp9q5m2ip574m21oh/gradle-2.14.1-all.zip to /Users/menmen/.gradle/wrapper/dists/gradle-2.14.1-all/53l0mv9mggp9q5m2ip574m21oh
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:160)
	at org.gradle.wrapper.Install.access$400(Install.java:29)
	at org.gradle.wrapper.Install$1.call(Install.java:70)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more
Failed to install 'weex-gcanvas':Error: /Users/menmen/Desktop/weexpack/myproj/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/menmen/.nvm/versions/node/v7.0.0/lib/node_modules/weexpack/node_modules/weexpack-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Failed to install 'weex-chart':Error: /Users/menmen/Desktop/weexpack/myproj/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/menmen/.nvm/versions/node/v7.0.0/lib/node_modules/weexpack/node_modules/weexpack-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: /Users/menmen/Desktop/weexpack/myproj/platforms/android/gradlew: Command failed with exit code 1

**Comment by exolution** [comment]
这是下载最新版本的gradle出了问题 看起来是下载下来的zip包无法解压 你是啥windows操作系统？
建议自己下个2.14.1 安装一下~
