### ISSUE TITLE
之前weex debug是正常的 最近更新后出现debug报错

### ISSUE THREAD

**Issue by hengqingsheer** [weexteam/weex-pack#104]
fs.js:583
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/meisheng/.xtoolkit/node_modules/weex-devtool/package.json'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at NpmPackage.findBinPath (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/package/NpmPackage.js:58:41)
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/package/NpmPackage.js:27:46)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/xtoolkit.js:141:33)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.5@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)

请问这个如何处理呀

**Comment by exolution** [comment]
这种问题 很奇怪 
可以尝试 weex update weex-devtool解决

**Comment by erha19** [comment]
更新不行的话可以尝试
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
```
