### ISSUE TITLE
$ weexpack init appname 报错

### ISSUE THREAD

**Issue by cyan24** [weexteam/weex-pack#12]
weexpack@0.1.1 
$ weexpack init appname 后
报错内容：
/usr/local/lib/node_modules/weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by jiaochunxiao** [comment]
@cyan24 感觉像是node版本的问题，更新下版本吧。

**Comment by exolution** [comment]
@cyan24 目前要求node 6.x 建议先升级一下
后续版本会做向下兼容
