### ISSUE TITLE
weexpack run web throwing error

### ISSUE THREAD

**Issue by zisuzon** [weexteam/weex-pack#148]
I've installed a weexpack project. 

When I am trying to run the command **weexpack run web** It's showing error.

`module.js:442
    throw err;
    ^

Error: Cannot find module '../src/run/Web'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dev03/.nvm/versions/node/v6.2.1/lib/node_modules/weexpack/bin/weexpack-run:7:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
`

Anyone can help me with it?

**Comment by thynedev** [comment]
same for me. please help

**Comment by hworld** [comment]
Same here. I was able to change that line in weexpack-run to have a lowercase `web` and it fixes it. I think it's probably just differences between path case sensitivity.

**Comment by JackPu** [comment]
@thynedev  This is a bug. And you can fix it:
```
cd /usr/local/lib/node_modules/weexpack/src/run/ 
mv web.js Web.js
```

**Comment by suzon007** [comment]
I fix the bug but the server is not running. It starts the server and then closes down automatically in the terminal. Any idea what might be wrong? @JackPu @hworld 


`➜  packCatalog weexpack run web

 => Starting web service
npm WARN optional Skipping failed optional dependency //ios-deploy:
npm WARN notsup Not compatible with your operating system or architecture: ios-deploy@1.9.1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN xxx@1.0.0 No repository field.

> xxx@1.0.0 build /home/dev03/workspace/deligram/weex/packCatalog
> webpack

Hash: c8454d1da16108d5190e2c54d8881528e1700293
Version: webpack 2.5.1
Child
    Hash: c8454d1da16108d5190e
    Time: 9960ms
           Asset    Size  Chunks             Chunk Names
    index.web.js  5.5 kB       0  [emitted]  index
       [0] ./src/index.vue 1.46 kB {0} [built]
       [1] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 307 bytes {0} [built]
       [2] ./temp?entry=true 70 bytes {0} [built]
       [3] ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-df650e8c!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 382 bytes {0} [built]
       [4] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [5] ./~/vue-loader/lib/component-normalizer.js 1.12 kB {0} [built]
       [6] ./~/vue-loader/lib/template-compiler.js?id=data-v-df650e8c!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 711 bytes {0} [built]
       [7] ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-df650e8c!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 1.33 kB {0} [built]
       [8] ./~/vue-style-loader/lib/addStylesClient.js 6.05 kB {0} [built]
       [9] ./~/vue-style-loader/lib/listToStyles.js 639 bytes {0} [built]
Child
    Hash: 2c54d8881528e1700293
    Time: 6339ms
       Asset    Size  Chunks             Chunk Names
    index.js  2.1 kB       0  [emitted]  index
       [0] ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 307 bytes {0} [built]
       [1] ./~/weex-vue-loader/lib/style-loader.js!./~/weex-vue-loader/lib/style-rewriter.js?id=data-v-7f3bd0f4!./~/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 307 bytes {0} [built]
       [2] ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-7f3bd0f4!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 543 bytes {0} [built]
       [3] ./src/index.vue?entry=true 1.72 kB {0} [built]
 => server is running
    please open http://localhost:8080/web/index.html
`

**Comment by thynedev** [comment]
Thanks a lot! @JackPu

**Comment by whitelynx** [comment]
> This is a bug. And you can fix it:

Any chance of getting this bug fixed in the project itself so it can be used on Linux?

**Comment by whitelynx** [comment]
I opened #168 to fix this, if someone could review and merge it...
