### ISSUE TITLE
weexpack build ios报错

### ISSUE THREAD

**Issue by cyan24** [weexteam/weex-pack#16]
weexpack build ios后报错
module.js:442
    throw err;
    ^

Error: Cannot find module '../src/build/Android'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-build.js:5:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by exolution** [comment]
请使用 npm install -g weexpack 升级后再试

**Comment by cyan24** [comment]
升级过依然是报这个错，当前版本是 weexpack@0.1.1 ，npm install期间有warnning

**Comment by cyan24** [comment]
升级过依然是报这个错，当前版本是 weexpack@0.1.1

**Comment by exolution** [comment]
@cyan24 hi 能麻烦你进到/usr/local/lib/node_modules/weexpack/src/build/这个目录下 看有没有Android.js （或者是不是小写的android） 
anyway 你先npm uninstall -g weexpack 卸载一下 重新安装 应该能解决这个问题。

**Comment by exolution** [comment]
问题已解决
