### ISSUE TITLE
ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by FayzullaKhodja** [weexteam/weex-pack#179]
I have an issue when installing weexpack, it appears that the sha1 checksum verification fails

```
npm ERR! code EINTEGRITY
npm ERR! sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= integrity checksum failed when using sha1: wanted sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= but got sha1-H0xrYFIJCXPy22raAWsSKzZMeS8=. (2748202 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khodja/.npm/_logs/2017-07-22T06_49_47_089Z-debug.log
```

Log:

```
161 silly resolveWithNewModule tar@1.0.2 checking installable status
162 verbose stack Error: sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= integrity checksum failed when using sha1: wanted sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= but got sha1-H0xrYFIJCXPy22raAWsSKzZMeS8=. (2748202 bytes)
162 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
162 verbose stack     at emitNone (events.js:110:20)
162 verbose stack     at Transform.emit (events.js:207:7)
162 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
162 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
162 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
163 verbose cwd /Users/khodja
164 verbose Darwin 16.5.0
165 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "./weex-pack" "--save-optional"
166 verbose node v8.2.1
167 verbose npm  v5.3.0
168 error code EINTEGRITY
169 error sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= integrity checksum failed when using sha1: wanted sha1-33w+1aJ3w/nUtdgZsFMR0QogCuY= but got sha1-H0xrYFIJCXPy22raAWsSKzZMeS8=. (2748202 bytes)
170 verbose exit [ 1, true ]
```

**Comment by FayzullaKhodja** [comment]
I sloved it by downgrading Nodejs and npm to older version

**Comment by dseeker** [comment]
@FayzullaKhodja what version did you use? having the same issue with Node 8.8 and NPM 5.8

**Comment by FayzullaKhodja** [comment]
@dseeker node v8.2.1, npm  v5.3.0
