### ISSUE TITLE
weex run android 报错

### ISSUE THREAD

**Issue by wazsq** [weexteam/weex-pack#198]
文档上说 要运行 `weexpack run android` ，结果  `bash: weexpack: 未找到命令`，
打印 weex -v ，结果是这样的
 

> v1.1.0-beta.1
>  - weexpack : v0.4.7-beta.8
> - weex-builder : v0.2.13-beta.1
>  - weex-devtool : v0.3.2-beta.7
> - weex-previewer : v1.3.13-beta.1

 
然后运行 `weex run android`，结果又是这样的
> module.js:471
>    throw err;
>     ^
> 
> Error: Cannot find module '../src/run/Web'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/sce/.xtoolkit/node_modules/weexpack/bin/weexpack-run:7:16)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)

...我就醉了，本来挺好的一件事，弄得各种坑，希望官方能认真地完善文档，不然这开源也没意思呀

**Comment by ChangJoo-Park** [comment]
Same here, 

```
module.js:529
    throw err;
    ^

Error: Cannot find module '../build/run/web'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/changjoo-park/.xtoolkit/node_modules/weexpack/bin/weexpack-run.js:8:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by magicknight** [comment]
It seems that weex is not properly tested on Linux/Mac...
