### ISSUE TITLE
mac 10.13.2 beta下增加ios平台报错 

### ISSUE THREAD

**Issue by hainuo** [weexteam/weex-pack#204]
```
weex platform add ios
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/hainuo/.xtoolkit/node_modules/weexpack/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at NpmPackage.findBinPath (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:47:39)
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:21:43)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/Command.js:39:9)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:137:27)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:86:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
```

**Comment by hainuo** [comment]
增加 相应的package.json(内容设置为空的`{}`)后
```
weex platform add ios
/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:52
    if (packageJson.bin[bin]) {
                       ^

TypeError: Cannot read property 'platform' of undefined
    at NpmPackage.findBinPath (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:52:24)
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/package/NpmPackage.js:21:43)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/Command.js:39:9)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:137:27)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/xtoolkit.js:86:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
