### ISSUE TITLE
使用weex命令行，创建的项目，运行报错

### ISSUE THREAD

**Issue by Cody1988** [weexteam/weex-pack#214]
系统macOS 10.13
# 版本
npm 5.5.1
weex 
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.7
 - weex-devtool : v0.3.2-beta.11
 - weex-previewer : v1.3.20

# 异常

创建项目，使用`npm run build`命令时，报错

```exception

> webpack

module.js:538
    throw err;
    ^

Error: Cannot find module 'find-up'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cody/2017/learn/weex/weex-starter/node_modules/_read-pkg-up@1.0.1@read-pkg-up/index.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weex@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weex@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cody/.npm/_logs/2017-12-30T07_45_20_039Z-debug.log
```

使用`weex run android` 时同样会报错，

```exception
Error: The resource string "capture_qrcode_prompt" has been marked as translatable="false" [ExtraTranslation]
  <string name="capture_qrcode_prompt">请将条码置于取景框内扫描</string>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cody/2017/learn/weex/weex-starter/platforms/android/app/src/main/res/values-zh-rCN/strings.xml:21: Error: The resource string "cpu_not_support_tip" has been marked as translatable="false" [ExtraTranslation]
  <string name="cpu_not_support_tip">对不起,您当前的设备是X86架构.\n我们只支持ARM架构的设备!</string>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.).

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

2 errors, 0 warnings


```

`weex run android`运行，最终会打印下面的log

```log
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
 => Install app ...
```
但是在Android手机上并未发现安装的应用

**Comment by misakuo** [comment]
@erha19 Have a look at that

**Comment by inu1255** [comment]
edit file
`/Users/cody/2017/learn/weex/weex-starter/platforms/android/app/src/main/res/values-zh-rCN/strings.xml`
``` xml
<resources>
  <string name="app_name">WEEX APP</string>
</resources>
```

**Comment by Cody1988** [comment]
@inu1255 

ths, I can run the demo in my android device, but there is still an error, like this

```logs
  sh: webpack-dev-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! weex@1.0.0 serve: `webpack-dev-server --config webpack.dev.js --watch --open`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the weex@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cody/.npm/_logs/2018-01-04T01_27_35_326Z-debug.log
~
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.                   
```


这些错误都是因为weex cli创建项目的模板的原因么？是否可以通过修改模版，一次性把这些问题修复，

还是说是我的开发环境的差异导致的

**Comment by Cody1988** [comment]
@inu1255 
这个应该是template的项目的问题了，是否可以把template项目相关地方修改一下
