### ISSUE TITLE
Can't add plugin

### ISSUE THREAD

**Issue by rupertqin** [weexteam/weex-pack#218]
` weexpack plugin add weex-svg`

```
=>  Failed to install 'weex-adapter-image':weexpack error: The provided path "/Users/rupert/Code/test/bai/platforms/ios/Weexplugin" is not a weexpack iOS project.
    at new Api (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/platforms/ios_pack/Api.js:85:15)
    at Object.getPlatformApi (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/platforms/platforms.js:76:23)
    at handleInstall (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/plugman/install.js:614:27)
    at /Users/rupert/.n/lib/node_modules/weexpack/lib/src/plugman/install.js:410:28
    at _fulfilled (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:749:13)
    at /Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:509:49
    at flush (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:150:11)
Failed to install 'weex-svg':weexpack error: The provided path "/Users/rupert/Code/test/bai/platforms/ios/Weexplugin" is not a weexpack iOS project.
    at new Api (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/platforms/ios_pack/Api.js:85:15)
    at Object.getPlatformApi (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/platforms/platforms.js:76:23)
    at handleInstall (/Users/rupert/.n/lib/node_modules/weexpack/lib/src/plugman/install.js:614:27)
    at /Users/rupert/.n/lib/node_modules/weexpack/lib/src/plugman/install.js:410:28
    at _fulfilled (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:749:13)
    at /Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:509:49
    at flush (/Users/rupert/.n/lib/node_modules/weexpack/node_modules/q/q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:150:11)
Error: The provided path "/Users/rupert/Code/test/bai/platforms/ios/Weexplugin" is not a weexpack iOS project.
```

Your development environment
weex-toolkit verison (v1.1.0-beta.7)
platform (Mac)

**Comment by fumpierrez** [comment]
Have you tried` weex update weexpack`? and then removing and re-adding the platform ios
