### ISSUE TITLE
weex run android

### ISSUE THREAD

**Issue by LearningFromOthers** [weexteam/weex-pack#224]
module.js:471     
    throw err;    
    ^             

Error: Cannot find module './android'                                     
    at Function.Module._resolveFilename (module.js:469:15)                
    at Function.Module._load (module.js:417:25)                           
    at Module.require (module.js:497:17)                                  
    at require (internal/module.js:20:19)                                 
    at Object.<anonymous> (/home/z/.xtoolkit/node_modules/weexpack/lib/run/index.js:3:18)
    at Module._compile (module.js:570:32)                                 
    at Object.Module._extensions..js (module.js:579:10)                   
    at Module.load (module.js:487:32)                                     
    at tryModuleLoad (module.js:446:12)                                   
    at Function.Module._load (module.js:438:3)

**Comment by erha19** [comment]
@LearningFromOthers upgrade to version `v1.0.14`. see https://github.com/weexteam/weex-pack/commit/fa05fd9a2cc578b1704a4de48cd571bf42987d33
