### ISSUE TITLE
CompileC build/Build/Intermediates.noindex/WeexDemo.build/Debug-

### ISSUE THREAD

**Issue by sudeepdk** [weexteam/weex-pack#227]
The following build commands failed:
	CompileC build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/UIViewController+WXDemoNaviBar.o WeexDemo/WeexScanner/UIViewController+WXDemoNaviBar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
13:36:20 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=****-****-****-****-**********
 -sdk iphonesimulator -derivedDataPath build clean build
2018-03-10 13:35:47.642 xcodebuild[12627:340520]  DTDeviceKit: deviceType from************ was NULL
** BUILD FAILED **

The following build commands failed:
	CompileC build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/UIViewController+WXDemoNaviBar.o WeexDemo/WeexScanner/UIViewController+WXDemoNaviBar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at _buildOnSimulator (/Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:328:18)
    at /Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:300:7
    at new Promise (<anonymous>)
    at buildApp (/Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:289:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by erha19** [comment]
@sudeepdk see https://github.com/weexteam/weex-toolkit/issues/300#issuecomment-370652227.
