### ISSUE TITLE
weexpack init 报错

### ISSUE THREAD

**Issue by styling** [weexteam/weex-pack#25]
/usr/local/lib/node_modules/weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by rickykaka1899** [comment]
i have same question, anyone know how to solve it

**Comment by exolution** [comment]
please update your node 
need node version 6.0+

**Comment by MaryWu** [comment]
we'll close this issue for now. if you had further problem, pls feel free to submit new one. thanks
