### ISSUE TITLE
class SilentTerminalAdapter extends TerminalAdapter

### ISSUE THREAD

**Issue by dongfangx** [weexteam/weex-pack#28]
version:0.2.1
执行 weexpack init appName
/usr/local/lib/node_modules/weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by dongfangx** [comment]
nodejs升级到6.0以上，解决了这个问题
