### ISSUE TITLE
weexpack init one

### ISSUE THREAD

**Issue by spiritelf** [weexteam/weex-pack#31]
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\huang\AppData\Roaming\npm\node_modules\weexp
ack\bin\weexpack-init:5:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by exolution** [comment]
请升级你的Node 至6.x以上版本~
