### ISSUE TITLE
weexpack init appName 时报错

### ISSUE THREAD

**Issue by caozhiyong** [weexteam/weex-pack#44]
localhost:weexTest flycao$ sudo weexpack init appName
Password:
/usr/local/lib/node_modules/weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by caozhiyong** [comment]
mac10.12.2，weexpack --version 0.2.5

**Comment by JackPu** [comment]
@caozhiyong  建议你升级你的node version >= 6.0

**Comment by JackPu** [comment]
@caozhiyong  node 版本切换  安利 n 模块，
``` bash
sudo npm install n -g
```
然后切换到你需要的node版本 sudo n 6.0.0

**Comment by alex-zhang** [comment]
Linux alex 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
node:  v7.2.0
weexpack: v0.2.5 

同样的错误。

**Comment by exolution** [comment]
建议使用npm 安装 不要使用yarn
