### ISSUE TITLE
error，when we use weex

### ISSUE THREAD

**Issue by zfha** [weexteam/weex-pack#50]
error，

**Comment by zfha** [comment]
```
➜  myApp weexpack init myApp
/usr/local/lib/node_modules/.weexpack_npminstall/weexpack/0.2.5/weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/.weexpack_npminstall/weexpack/0.2.5/weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```
Can you help me to solve this problem?

**Comment by exolution** [comment]
please update your node to 6.x
