### ISSUE TITLE
运行weexpack plugin add命令超时

### ISSUE THREAD

**Issue by hodgevk** [weexteam/weex-pack#52]
```
 weexpack plugin add weex-chart
(node:11408) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:3128) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
{ Error: connect ETIMEDOUT 100.67.94.5:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '100.67.94.5',
  port: 80 }
Error: connect ETIMEDOUT 100.67.94.5:80
```

**Comment by JackPu** [comment]
@hodgevk  这个和网络关系很大，现在还有遇见类似情况么？
