### ISSUE TITLE
weexpack build android报错

### ISSUE THREAD

**Issue by xblibo** [weexteam/weex-pack#95]
Cannot find module '../src/build/web'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node-v6.9.5-linux-x64/lib/node_modules/weexpack/bin/weexpack-build:7:18)

https://github.com/weexteam/weex-pack/blob/master/bin/weexpack-build这个文件的src/build/web,应该改成src/build/Web , w大写．　或者重命名src/build/Web.js？

**Comment by mjsornp** [comment]
我也碰到这个问题，用你的方法解决了。
非常感谢！

**Comment by jamesearl** [comment]
Could be a case-sensitivity issue. I got passed it by opening `~/.xtoolkit/node_modules/weexpack/bin/weexpack-run` and changing the case of the import from `.../src/build/Web.js` to `.../src/build/web.js`.

**Comment by kingcc** [comment]
Interesting . Weex-pack has so many holes .
